name: check-shutdown
version: "1.0"
summary: Simple snap 
description: |
        Simple snap that checks every second if a shutdown has been scheduled
        to build ...
       
confinement: strict
grade: stable
base: core20

architectures:
  - build-on: amd64, arm64, armhf

apps:
  check-shutdown:
     command: check-shutdown
     daemon: simple
#     install-mode: disable
#     plugs: [shutdown, mount-observe, system-observe]

parts:
  check-shutdown:
     plugin: dump
     source: scripts

