name: check-shutdown
version: "1.0"
summary: Simple snap 
description: |
        Simple snap that checks every second if a shutdown has been scheduled
       
confinement: strict
grade: stable
base: core20

architectures:
  - build-on: amd64, arm64, armhf

apps:
  check-shutdown:
     command: check-shutdown
     daemon: simple

parts:
  check-shutdown:
     plugin: dump
     source: scripts

